pipeline {
    agent {
        node {
            label 'jenkins-slave1.yvu.ch'
        }
    }

    stages {
        stage('Build') {
            steps {
                sh 'cd Gadgeothek; ./gradlew clean'
                sh 'cd Gadgeothek; ./gradlew build'
                sh 'cd Gadgeothek; ./gradlew lint'
            }
            post {
                always {
                    archiveArtifacts 'Gadgeothek/app/build/outputs/apk/*.apk'
                    junit allowEmptyResults: true, testResults: '**/build/test-results/**/*.xml'
                }
            }
        }

        stage('End2End Tests') {
            steps {
                
            }
        }

        stage('Package') {
            steps {
                sh 'echo Package'
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
