pipeline {
    agent {
        node {
            label 'jenkins-slave5.yvu.ch'
        }
    }

    stages {
        stage('Build') {
            steps {
                sh 'echo Build'
            }
        }

        stage('End2End Tests') {
            steps {
                sh 'echo End2End Tests'
            }
        }

        stage('Package') {
            steps {
                sh 'echo Package'
            }
        }
    }
}