pipeline {
    agent {
        node {
            label 'jenkins-slave1.yvu.ch'
        }
    }

    stages {
        stage('Build') {
            steps {
                sh 'cd Gadgeothek; ./gradlew clean'
                sh 'cd Gadgeothek; ./gradlew build'
                sh 'cd Gadgeothek; ./gradlew lint'
            }
            post {
                always {
                    archiveArtifacts 'Gadgeothek/app/build/outputs/apk/*.apk'
                    junit allowEmptyResults: true, testResults: '**/build/test-results/**/*.xml'
                }
            }
        }

        stage('End2End Tests') {
            steps {

            }
        }

        stage('Package') {
            steps {
                sh 'cd Gadgeothek; ./gradlew assembleRelease'
                sh 'cd Gadgeothek; zipalign -v -p 4 app/build/outputs/apk/app-full-release-unsigned.apk app/build/outputs/apk/my-app-unsigned-aligned.apk'
                sh 'cd Gadgeothek; apksigner sign --keypass file:${HOME}/keystore-pass --ks ${HOME}/Gadgeothek.keystore --out my-app-release.apk my-app-unsigned-aligned.apk'
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
